# Generated by Django 6.0.6 on 2026-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profile_image_userprofile_profile_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_character',
            field=models.CharField(max_length=100),
        ),
    ]
