# Generated by Django 6.0.6 on 2026-06-20 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommember',
            options={'ordering': ['joined_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='current_topic',
            field=models.IntegerField(blank=True, null=True, verbose_name='선택된 주제'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', '대기중'), ('started', '시작됨'), ('topic_selected', '주제선택됨')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='roommember',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_rounds',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('user', 'room')},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(choices=[(1, '연애'), (2, '우정'), (3, '일상·일'), (4, '밸런스 게임')])),
                ('zone', models.CharField(choices=[('GREEN', '초록 (10~33)'), ('YELLOW', '노랑 (34~66)'), ('PINK', '핑크 (67~100)')], max_length=6)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=120)),
                ('option_b', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'zone', 'is_active'], name='main_questi_topic_6f9014_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_zone', models.CharField(choices=[('GREEN', '초록 (10~33)'), ('YELLOW', '노랑 (34~66)'), ('PINK', '핑크 (67~100)')], max_length=6)),
                ('option_a', models.CharField(default='A', max_length=120)),
                ('option_b', models.CharField(default='B', max_length=120)),
                ('changes', models.IntegerField(default=0)),
                ('extensions', models.IntegerField(default=0)),
                ('rise', models.FloatField(default=0)),
                ('temp_before', models.FloatField(default=0)),
                ('temp_after', models.FloatField(default=0)),
                ('change_rate', models.FloatField(default=0)),
                ('result_status', models.CharField(choices=[('PENDING', '진행/미완'), ('MATCHED', '의견 일치'), ('UNMATCHED', '의견 갈림')], default='PENDING', max_length=10)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='main.room')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='main.question')),
            ],
            options={
                'ordering': ['room', 'round_number'],
                'unique_together': {('room', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('INITIAL', '초기 투표'), ('MID', '중간 투표'), ('FINAL', '결과 투표')], max_length=7)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.roommember')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.gameround')),
            ],
            options={
                'unique_together': {('round', 'member', 'phase')},
            },
        ),
    ]
