# Generated by Django 6.0.6 on 2026-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_roommember_options_room_current_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.IntegerField(choices=[(1, '사랑과 연애'), (2, '취향과 라이프스타일'), (3, '최악의 상황은'), (4, '갓생과 일')]),
        ),
    ]
