# Generated by Django 6.0.6 on 2026-06-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
