# Generated by Django 6.0.6 on 2026-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gameround_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
