# Generated by Django 6.0.6 on 2026-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='phase',
            field=models.CharField(choices=[('DISCUSSION', '토론중'), ('VOTING', '최종투표중'), ('FINISHED', '종료')], default='DISCUSSION', max_length=10),
        ),
    ]
